# Default values for lb-panosc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: garethcmurphy/lb-panosc
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  name: lb-panosc
  type: ClusterIP
  port: 80
  externalPort: 80

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ssl-redirect: "true"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: scicat01.esss.lu.se
  hosts:
    - host: scicat01.esss.lu.se
      paths: [ /panosc ]

  tls: 
    - secretName: lbpanoscservice
      hosts:
        - scicat01.esss.lu.se

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
