{{- if .Values.ingress.enabled -}}
{{- $fullName := include "lb-panosc.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
{{- $host := .Values.ingress.host -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "lb-panosc.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - secretName: lbpanoscservice
      hosts:
      - {{ $host }}
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /panosc
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
{{- end }}