apiVersion: v1
kind: Service
metadata:
  name: {{ include "lb-panosc.fullname" . }}
  labels:
{{ include "lb-panosc.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: {{ include "lb-panosc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
